version: 2

sources:

    - name: source

      database: MYDB

      schema: BRONZE

      tables:

        - name: WORK_PRODUCT_COPY
    - name: xfm

      database: PC_DBT_DB

      schema: SILVER

      tables:

        - name: WORK_PRODUCT_TRANSFORM